export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  MATERIAL_BATCH_NOT_FOUND: "MATERIAL_BATCH_NOT_FOUND",
  MATERIAL_EXPIRED: "MATERIAL_EXPIRED",
  MATERIAL_OVERDRAWN: "MATERIAL_OVERDRAWN",
  MATERIAL_BATCH_OCCUPIED: "MATERIAL_BATCH_OCCUPIED",
  MATERIAL_REVIEW_SELF: "MATERIAL_REVIEW_SELF",
  MATERIAL_REQUISITION_NOT_FOUND: "MATERIAL_REQUISITION_NOT_FOUND",
  MATERIAL_REQUISITION_NOT_REVIEWABLE: "MATERIAL_REQUISITION_NOT_REVIEWABLE",
  MATERIAL_BATCH_DUPLICATE: "MATERIAL_BATCH_DUPLICATE"
} as const;
